// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/dfps.proto

package dfpspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_UNSPECIFIED TaskStatus = 0 // The first constant must map to zero in proto3
	TaskStatus_TASK_PENDING     TaskStatus = 1
	TaskStatus_TASK_PROCESSING  TaskStatus = 2
	TaskStatus_TASK_DONE        TaskStatus = 3
	TaskStatus_TASK_FAILED      TaskStatus = 4
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_UNSPECIFIED",
		1: "TASK_PENDING",
		2: "TASK_PROCESSING",
		3: "TASK_DONE",
		4: "TASK_FAILED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_UNSPECIFIED": 0,
		"TASK_PENDING":     1,
		"TASK_PROCESSING":  2,
		"TASK_DONE":        3,
		"TASK_FAILED":      4,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dfps_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_proto_dfps_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_dfps_proto_rawDescGZIP(), []int{0}
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_dfps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_dfps_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_dfps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_dfps_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_proto_dfps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_dfps_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	State         TaskStatus             `protobuf:"varint,4,opt,name=state,proto3,enum=dfps.TaskStatus" json:"state,omitempty"`
	Length        int64                  `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_proto_dfps_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfps_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_dfps_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetTaskResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetTaskResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *GetTaskResponse) GetState() TaskStatus {
	if x != nil {
		return x.State
	}
	return TaskStatus_TASK_UNSPECIFIED
}

func (x *GetTaskResponse) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type GetTaskReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Status        TaskStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=dfps.TaskStatus" json:"status,omitempty"`
	Start         int64                  `protobuf:"varint,5,opt,name=start,proto3" json:"start,omitempty"`
	Length        int64                  `protobuf:"varint,6,opt,name=length,proto3" json:"length,omitempty"`
	OutputPath    string                 `protobuf:"bytes,7,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	State         TaskStatus             `protobuf:"varint,8,opt,name=state,proto3,enum=dfps.TaskStatus" json:"state,omitempty"`
	WorkerId      string                 `protobuf:"bytes,9,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ClaimedAt     string                 `protobuf:"bytes,10,opt,name=claimed_at,json=claimedAt,proto3" json:"claimed_at,omitempty"`
	AttemptNo     int32                  `protobuf:"varint,11,opt,name=attempt_no,json=attemptNo,proto3" json:"attempt_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskReportResponse) Reset() {
	*x = GetTaskReportResponse{}
	mi := &file_proto_dfps_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskReportResponse) ProtoMessage() {}

func (x *GetTaskReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfps_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskReportResponse.ProtoReflect.Descriptor instead.
func (*GetTaskReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_dfps_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskReportResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetTaskReportResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetTaskReportResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *GetTaskReportResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_UNSPECIFIED
}

func (x *GetTaskReportResponse) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GetTaskReportResponse) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *GetTaskReportResponse) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *GetTaskReportResponse) GetState() TaskStatus {
	if x != nil {
		return x.State
	}
	return TaskStatus_TASK_UNSPECIFIED
}

func (x *GetTaskReportResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *GetTaskReportResponse) GetClaimedAt() string {
	if x != nil {
		return x.ClaimedAt
	}
	return ""
}

func (x *GetTaskReportResponse) GetAttemptNo() int32 {
	if x != nil {
		return x.AttemptNo
	}
	return 0
}

var File_proto_dfps_proto protoreflect.FileDescriptor

const file_proto_dfps_proto_rawDesc = "" +
	"\n" +
	"\x10proto/dfps.proto\x12\x04dfps\"H\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"#\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x95\x01\n" +
	"\x0fGetTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12&\n" +
	"\x05state\x18\x04 \x01(\x0e2\x10.dfps.TaskStatusR\x05state\x12\x16\n" +
	"\x06length\x18\x05 \x01(\x03R\x06length\"\xd7\x02\n" +
	"\x15GetTaskReportResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12(\n" +
	"\x06status\x18\x04 \x01(\x0e2\x10.dfps.TaskStatusR\x06status\x12\x14\n" +
	"\x05start\x18\x05 \x01(\x03R\x05start\x12\x16\n" +
	"\x06length\x18\x06 \x01(\x03R\x06length\x12\x1f\n" +
	"\voutput_path\x18\a \x01(\tR\n" +
	"outputPath\x12&\n" +
	"\x05state\x18\b \x01(\x0e2\x10.dfps.TaskStatusR\x05state\x12\x1b\n" +
	"\tworker_id\x18\t \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"claimed_at\x18\n" +
	" \x01(\tR\tclaimedAt\x12\x1d\n" +
	"\n" +
	"attempt_no\x18\v \x01(\x05R\tattemptNo*i\n" +
	"\n" +
	"TaskStatus\x12\x14\n" +
	"\x10TASK_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTASK_PENDING\x10\x01\x12\x13\n" +
	"\x0fTASK_PROCESSING\x10\x02\x12\r\n" +
	"\tTASK_DONE\x10\x03\x12\x0f\n" +
	"\vTASK_FAILED\x10\x042\xc4\x01\n" +
	"\vCoordinator\x12<\n" +
	"\tHeartbeat\x12\x16.dfps.HeartbeatRequest\x1a\x17.dfps.HeartbeatResponse\x126\n" +
	"\aGetTask\x12\x14.dfps.GetTaskRequest\x1a\x15.dfps.GetTaskResponse\x12?\n" +
	"\n" +
	"ReportTask\x12\x14.dfps.GetTaskRequest\x1a\x1b.dfps.GetTaskReportResponseB*Z(github.com/Gurveer1510/dfps/proto/dfpspbb\x06proto3"

var (
	file_proto_dfps_proto_rawDescOnce sync.Once
	file_proto_dfps_proto_rawDescData []byte
)

func file_proto_dfps_proto_rawDescGZIP() []byte {
	file_proto_dfps_proto_rawDescOnce.Do(func() {
		file_proto_dfps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dfps_proto_rawDesc), len(file_proto_dfps_proto_rawDesc)))
	})
	return file_proto_dfps_proto_rawDescData
}

var file_proto_dfps_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_dfps_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_dfps_proto_goTypes = []any{
	(TaskStatus)(0),               // 0: dfps.TaskStatus
	(*HeartbeatRequest)(nil),      // 1: dfps.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 2: dfps.HeartbeatResponse
	(*GetTaskRequest)(nil),        // 3: dfps.GetTaskRequest
	(*GetTaskResponse)(nil),       // 4: dfps.GetTaskResponse
	(*GetTaskReportResponse)(nil), // 5: dfps.GetTaskReportResponse
}
var file_proto_dfps_proto_depIdxs = []int32{
	0, // 0: dfps.GetTaskResponse.state:type_name -> dfps.TaskStatus
	0, // 1: dfps.GetTaskReportResponse.status:type_name -> dfps.TaskStatus
	0, // 2: dfps.GetTaskReportResponse.state:type_name -> dfps.TaskStatus
	1, // 3: dfps.Coordinator.Heartbeat:input_type -> dfps.HeartbeatRequest
	3, // 4: dfps.Coordinator.GetTask:input_type -> dfps.GetTaskRequest
	3, // 5: dfps.Coordinator.ReportTask:input_type -> dfps.GetTaskRequest
	2, // 6: dfps.Coordinator.Heartbeat:output_type -> dfps.HeartbeatResponse
	4, // 7: dfps.Coordinator.GetTask:output_type -> dfps.GetTaskResponse
	5, // 8: dfps.Coordinator.ReportTask:output_type -> dfps.GetTaskReportResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_dfps_proto_init() }
func file_proto_dfps_proto_init() {
	if File_proto_dfps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dfps_proto_rawDesc), len(file_proto_dfps_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dfps_proto_goTypes,
		DependencyIndexes: file_proto_dfps_proto_depIdxs,
		EnumInfos:         file_proto_dfps_proto_enumTypes,
		MessageInfos:      file_proto_dfps_proto_msgTypes,
	}.Build()
	File_proto_dfps_proto = out.File
	file_proto_dfps_proto_goTypes = nil
	file_proto_dfps_proto_depIdxs = nil
}
