// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/dfps.proto

package dfpspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	Action_ACTION_RUN         Action = 1
	Action_ACTION_WAIT        Action = 2
	Action_ACTION_SHUTDOWN    Action = 3
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_RUN",
		2: "ACTION_WAIT",
		3: "ACTION_SHUTDOWN",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_RUN":         1,
		"ACTION_WAIT":        2,
		"ACTION_SHUTDOWN":    3,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dfps_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_proto_dfps_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_dfps_proto_rawDescGZIP(), []int{0}
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_dfps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_dfps_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_dfps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_dfps_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_proto_dfps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_dfps_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Start         int64                  `protobuf:"varint,4,opt,name=start,proto3" json:"start,omitempty"`
	Length        int64                  `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	OutputPath    string                 `protobuf:"bytes,6,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_dfps_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfps_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_dfps_proto_rawDescGZIP(), []int{3}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Task) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Task) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Task) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Task) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Action        Action                 `protobuf:"varint,2,opt,name=action,proto3,enum=dfps.Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_proto_dfps_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfps_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_dfps_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *GetTaskResponse) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

type ReportTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	FailureReason string                 `protobuf:"bytes,4,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskRequest) Reset() {
	*x = ReportTaskRequest{}
	mi := &file_proto_dfps_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskRequest) ProtoMessage() {}

func (x *ReportTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfps_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_dfps_proto_rawDescGZIP(), []int{5}
}

func (x *ReportTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReportTaskRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportTaskRequest) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

type ReportTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskResponse) Reset() {
	*x = ReportTaskResponse{}
	mi := &file_proto_dfps_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskResponse) ProtoMessage() {}

func (x *ReportTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfps_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_dfps_proto_rawDescGZIP(), []int{6}
}

var File_proto_dfps_proto protoreflect.FileDescriptor

const file_proto_dfps_proto_rawDesc = "" +
	"\n" +
	"\x10proto/dfps.proto\x12\x04dfps\"H\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"#\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"-\n" +
	"\x0eGetTaskRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\x99\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x14\n" +
	"\x05start\x18\x04 \x01(\x03R\x05start\x12\x16\n" +
	"\x06length\x18\x05 \x01(\x03R\x06length\x12\x1f\n" +
	"\voutput_path\x18\x06 \x01(\tR\n" +
	"outputPath\"W\n" +
	"\x0fGetTaskResponse\x12\x1e\n" +
	"\x04task\x18\x01 \x01(\v2\n" +
	".dfps.TaskR\x04task\x12$\n" +
	"\x06action\x18\x02 \x01(\x0e2\f.dfps.ActionR\x06action\"\x8a\x01\n" +
	"\x11ReportTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12%\n" +
	"\x0efailure_reason\x18\x04 \x01(\tR\rfailureReason\"\x14\n" +
	"\x12ReportTaskResponse*V\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"ACTION_RUN\x10\x01\x12\x0f\n" +
	"\vACTION_WAIT\x10\x02\x12\x13\n" +
	"\x0fACTION_SHUTDOWN\x10\x032\xc4\x01\n" +
	"\vCoordinator\x12<\n" +
	"\tHeartbeat\x12\x16.dfps.HeartbeatRequest\x1a\x17.dfps.HeartbeatResponse\x126\n" +
	"\aGetTask\x12\x14.dfps.GetTaskRequest\x1a\x15.dfps.GetTaskResponse\x12?\n" +
	"\n" +
	"ReportTask\x12\x17.dfps.ReportTaskRequest\x1a\x18.dfps.ReportTaskResponseB*Z(github.com/Gurveer1510/dfps/proto/dfpspbb\x06proto3"

var (
	file_proto_dfps_proto_rawDescOnce sync.Once
	file_proto_dfps_proto_rawDescData []byte
)

func file_proto_dfps_proto_rawDescGZIP() []byte {
	file_proto_dfps_proto_rawDescOnce.Do(func() {
		file_proto_dfps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dfps_proto_rawDesc), len(file_proto_dfps_proto_rawDesc)))
	})
	return file_proto_dfps_proto_rawDescData
}

var file_proto_dfps_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_dfps_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_dfps_proto_goTypes = []any{
	(Action)(0),                // 0: dfps.Action
	(*HeartbeatRequest)(nil),   // 1: dfps.HeartbeatRequest
	(*HeartbeatResponse)(nil),  // 2: dfps.HeartbeatResponse
	(*GetTaskRequest)(nil),     // 3: dfps.GetTaskRequest
	(*Task)(nil),               // 4: dfps.Task
	(*GetTaskResponse)(nil),    // 5: dfps.GetTaskResponse
	(*ReportTaskRequest)(nil),  // 6: dfps.ReportTaskRequest
	(*ReportTaskResponse)(nil), // 7: dfps.ReportTaskResponse
}
var file_proto_dfps_proto_depIdxs = []int32{
	4, // 0: dfps.GetTaskResponse.task:type_name -> dfps.Task
	0, // 1: dfps.GetTaskResponse.action:type_name -> dfps.Action
	1, // 2: dfps.Coordinator.Heartbeat:input_type -> dfps.HeartbeatRequest
	3, // 3: dfps.Coordinator.GetTask:input_type -> dfps.GetTaskRequest
	6, // 4: dfps.Coordinator.ReportTask:input_type -> dfps.ReportTaskRequest
	2, // 5: dfps.Coordinator.Heartbeat:output_type -> dfps.HeartbeatResponse
	5, // 6: dfps.Coordinator.GetTask:output_type -> dfps.GetTaskResponse
	7, // 7: dfps.Coordinator.ReportTask:output_type -> dfps.ReportTaskResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_dfps_proto_init() }
func file_proto_dfps_proto_init() {
	if File_proto_dfps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dfps_proto_rawDesc), len(file_proto_dfps_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dfps_proto_goTypes,
		DependencyIndexes: file_proto_dfps_proto_depIdxs,
		EnumInfos:         file_proto_dfps_proto_enumTypes,
		MessageInfos:      file_proto_dfps_proto_msgTypes,
	}.Build()
	File_proto_dfps_proto = out.File
	file_proto_dfps_proto_goTypes = nil
	file_proto_dfps_proto_depIdxs = nil
}
